[package]
name = "webdocker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
rand = "0.8"
image = "0.24.5"
ndarray = "0.15"
onnxruntime = "0.0.14"
serde_json = "1.0.94"



